### ISSUE TITLE
Comentários no HTML

### ISSUE THREAD

**Issue by lulinux21** [lulinux21/Tcc-SkyLoop#2]
Fala time beleza, eu vi algumas alterações no nosso sistema, porém só peço para tomarem cuidado na hora de subir o projeto e verificar se tem algum errinho !!

**Comment by WAACE** [comment]
Valeu lucas, o problema foi que eu fiz as alterações e confiei nelas, e não decodifiquei a página. Depois do upload ao repositório eu vi os comentários errados e fui atrás para saber melhor.
