### ISSUE TITLE
Codificações simultâneas.

### ISSUE THREAD

**Issue by WAACE** [lulinux21/Tcc-SkyLoop#3]
**Bom, percebi que ao codificar os códigos esta tarde, um pouco mais tarde descobri que o lucas também estava fazendo mudanças, por sorte cada um não sobre escreveu as mudanças do outro. Oque proponho é que ao começar fazer alguma alteração em algum arquivo seja ele nos arquivos do site ou da documentação, de um aviso prévio no grupo, para evitar algo indesejado. Boa noite a vocês.**

**Comment by lulinux21** [comment]
Beleza man combinado !!!!
